export const featuredProducts = [
  {
    id: 1,
    title: "Logitech G502 HERO",
    slug: "logitech-g502-hero",
    category: "mouse",
    brand: "Logitech",
    image: "/images/products/watch.png",
    price: 3999,
    oldPrice: 4999,
    rating: 4.8,
    reviews: 124,
    stock: 20,
    badge: "-20%",
  },
  {
    id: 2,
    title: "Sony WH-CH720N",
    slug: "sony-wh-ch720n",
    category: "headphones",
    brand: "Sony",
    image: "/images/products/watch.png",
    price: 8499,
    oldPrice: 9999,
    rating: 4.9,
    reviews: 89,
    stock: 15,
    badge: "-15%",
  },
  {
    id: 3,
    title: "Redragon K617",
    slug: "redragon-k617",
    category: "keyboard",
    brand: "Redragon",
    image: "/images/products/watch.png",
    price: 3799,
    oldPrice: 4599,
    rating: 4.7,
    reviews: 65,
    stock: 11,
    badge: "-18%",
  },
  {
    id: 4,
    title: "Apple Watch SE",
    slug: "apple-watch-se",
    category: "watch",
    brand: "Apple",
    image: "/images/products/watch.png",
    price: 32999,
    oldPrice: 35999,
    rating: 4.9,
    reviews: 43,
    stock: 8,
    badge: "-8%",
  },
  {
    id: 5,
    title: "Anker Soundcore",
    slug: "anker-soundcore",
    category: "speaker",
    brand: "Anker",
    image: "/images/products/watch.png",
    price: 5599,
    oldPrice: 6499,
    rating: 4.8,
    reviews: 58,
    stock: 14,
    badge: "-14%",
  },
  {
    id: 6,
    title: "Razer Viper Mini",
    slug: "razer-viper-mini",
    category: "mouse",
    brand: "Razer",
    image: "/images/products/watch.png",
    price: 2999,
    oldPrice: 3499,
    rating: 4.8,
    reviews: 97,
    stock: 25,
    badge: "-12%",
  },
];