export const topSellingProducts = [
  {
    id: 1,
    title: "Logitech G Pro X Wireless Headset",
    slug: "logitech-g-pro-x-wireless-headset",
    brand: "Logitech",
    image: "/images/products/headphone.png",
    price: 12999,
    oldPrice: 15999,
    rating: 4.9,
    reviews: 328,
    stock: 18,
    badge: "Best Seller",
  },
  {
    id: 2,
    title: "Apple Watch Series 10",
    slug: "apple-watch-series-10",
    brand: "Apple",
    image: "/images/products/watch.png",
    price: 45999,
    oldPrice: 49999,
    rating: 4.8,
    reviews: 186,
    stock: 12,
    badge: "Hot",
  },
  {
    id: 3,
    title: "Redragon K617 RGB Keyboard",
    slug: "redragon-k617-rgb-keyboard",
    brand: "Redragon",
    image: "/images/products/keyboard.png",
    price: 4999,
    oldPrice: 5999,
    rating: 4.7,
    reviews: 215,
    stock: 24,
    badge: "Popular",
  },
  {
    id: 4,
    title: "Razer Viper Mini Gaming Mouse",
    slug: "razer-viper-mini",
    brand: "Razer",
    image: "/images/products/mouse.png",
    price: 3499,
    oldPrice: 4299,
    rating: 4.9,
    reviews: 412,
    stock: 35,
    badge: "Top Rated",
  },
  {
    id: 5,
    title: "Anker Soundcore Liberty 4",
    slug: "anker-soundcore-liberty-4",
    brand: "Anker",
    image: "/images/products/earbuds.png",
    price: 8999,
    oldPrice: 10499,
    rating: 4.8,
    reviews: 142,
    stock: 21,
    badge: "Sale",
  },
  {
    id: 6,
    title: "Sony WH-1000XM5 Headphone",
    slug: "sony-wh1000xm5",
    brand: "Sony",
    image: "/images/products/sony-headphone.png",
    price: 32999,
    oldPrice: 35999,
    rating: 5.0,
    reviews: 491,
    stock: 9,
    badge: "Editor's Choice",
  },
];